language: python
dist: xenial

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install pytest flake8

before_script:
  - flake8 --version

script:
  - pytest tests
  - flake8 **/*py
